### ISSUE TITLE
Update frequentie erg laag

### ISSUE THREAD

**Issue by QkeleQ10** [mamorgen/magbot3#10]
Hoi,

Ik weet niet precies hoe vaak Magbot de Calendar updatet, maar volgens mij is het elke dag op de tijd dat je het hebt ingesteld. Het zou handiger zijn als we een tijd konden kiezen. Misschien zelfs meerdere keren per dag, of zodra er wijzigingen zijn!

Met vriendelijke groet,
QkeleQ10

**Comment by Netlob** [comment]
Hi QkeleQ10,

Er wordt meerdere keren per dag voor elke gebruiker het roosteropgehaald, gechecked of er wijzigingen zijn tov hun google calendar en afhankelijk daarvan worden er events/lessen geupdate. 

Magister heeft een ratelimit, en afhankelijk van het aantal gebruikers bepaald het programma hoevaak er wordt geupdate om niet over het ratelimit te gaan. Vorig schooljaar waren er maar een paar honderd gebruikers, wat ervoor zorgde dat hij overdag elke 30min updatete, en op andere tijden elk uur. De afgelopen weken hebben we een enorme groei gehad en dus kunnen we minder vaak updaten per dag omdat we anders het ratelimit halen. 

Voor meer info zie https://github.com/mamorgen/magbot3/blob/master/magbot3.js#L230
Hij pakt dus het aantal gebruikers en doet die keer 5 seconden (vorige week veranderd van 10sec naar 5sec) en omdat er dan momenteel dus meer gebruikers zijn duurt 1 volle sync erg lang.

**TL;DR** Wat zeker te zeggen is (ook gezien de CPU usage van de server) is dat hij meerdere keren per dag update, maar helaas moeten we het dus doen met het ratelimit van magister...

Mvg Sjoerd (en Kasper)

**Comment by QkeleQ10** [comment]
Oké, dat is goed om te weten! Wat wel raar is, is dat roosterwijzigingen soms 1 dag later pas doorkomen.

**Comment by Netlob** [comment]
Ja ik heb er zelf ook wel eens last van. Het is wel raar aangezien magbot niet meer oude lessen update 🤔 ...

@7kasper misschien kunnen we toevoegen dat prime users voorrang krijgen en altijd tijdens schooltijden elk half uur geupdate worden?

**Comment by QkeleQ10** [comment]
Trouwens, klein beetje feedback hier...

![image](https://user-images.githubusercontent.com/55982900/66139440-bb672b80-e600-11e9-9388-506c653e9e0a.png)
Het moet eigenlijk "Geüpdatet" zijn. [https://www.mijnwoordenboek.nl/werkwoord/updaten](url) Raar werkwoord 😄

**Comment by Netlob** [comment]
Leenwoorden...
fixed -> https://github.com/mamorgen/magbot3/commit/3b458837996e01d6c7574e887fdf9dbc9319f147

**Comment by QkeleQ10** [comment]
In r. 106 en 107 zit de oude vertaling nog... https://github.com/mamorgen/magbot3/blob/3b458837996e01d6c7574e887fdf9dbc9319f147/docs/signup/js/init.js#L106

Sorry als ik vervelend ben 😜

**Comment by 7kasper** [comment]
Haha ne hoor goed bezig! :)

Magbot doet niks met al geweeste afspraken.. Zou je de volgende keer bij een roosterwijziging even willen kijken of het niet bijvoorbeeld je telefoon is die google traag synchroniseerd (door bijvoorbeeld even op calendar.google.com te kijken en te refreshen). Als het daar niet aan ligt dan ga ik verder zoeken. Misschien is er ergens een soort wachtrij die verkeerd is geïmplementeerd, maar dat ik zou het zo niet weten.

**Comment by Netlob** [comment]
Zojuist de server geüpdatet, hij zou nu 2x zovaak moeten syncen!

**Comment by QkeleQ10** [comment]
Oké, bij de volgende roosterwijziging doe ik dat even
________________________________

**Comment by Netlob** [comment]
Ik sluit m omdat Magbot toch dood is :(
