### ISSUE TITLE
Finished high school, now what?

### ISSUE THREAD

**Issue by NorthLake** [mamorgen/magbot3#16]
I finished high school half a year ago, and I just noticed that I never revoked magbot's access to my calendar. So I went and checked on the site, and there is no option to opt out. By now my Magister account has been deactivated, so I can't change any options, as it'll give me a popup saying the username is incorrect.
Now, I'm not that sensitive about my data, so you shouldn't go out of your way to remove it from the backend, but it's weird that you're not able to opt out of the service.

**Comment by QkeleQ10** [comment]
You can go to Google Account > Security > Connected apps, and then remove Magbot to disable it.Met vriendelijke groet,Quinten Althues
-------- Original message --------From: NorthLake <notifications@github.com> Date: 10/11/2019  15:30  (GMT+01:00) To: mamorgen/magbot3 <magbot3@noreply.github.com> Cc: Subscribed <subscribed@noreply.github.com> Subject: [mamorgen/magbot3] Finished high school, now what? (#16) I finished high school half a year ago, and I just noticed that I never revoked magbot's access to my calendar. So I went and checked on the site, and there is no option to opt out. By now my Magister account has been deactivated, so I can't change any options, as it'll give me a popup saying the username is incorrect.
Now, I'm not that sensitive about my data, so you shouldn't go out of your way to remove it from the backend, but it's weird that you're not able to opt out of the service.

**Comment by 7kasper** [comment]
Yeah so our program works more like, ok if we don't have google access anymore we remove your account as well when the next purge comes along. I guess it should say that on the site (The faq is still missing haha) To cancel magbot just either change your magister password, remove the magbot calendars or revoke access. Or all of them of course. Magbot then just stops working and once in a while will delete your account entirely. (You can alsways opt-in again on the site).

I am not sure if magbot removing your account automatically revokes the google tokens. It might be the case that your account was already deleted but google still thinks we list it.
