### ISSUE TITLE
Google login 

### ISSUE THREAD

**Issue by rensdebee** [mamorgen/magbot3#17]
When I try to login with Google it say the app isn't authorized.

**Comment by AardappelMASTER** [comment]
same issue here......

**Comment by AlvinVrolijk** [comment]
same issue here, the app isn't verified

**Comment by Netlob** [comment]
ja we weten ervan... google is laaaangzaaaaaaaaam met verifieren :/

**Comment by Netlob** [comment]
Hi everyone reading and having this issue!

I just released the fix and on all my machines the google login works! Check it at https://magbot.nl/signup/

:)
