### ISSUE TITLE
Calendars syncing incredibly slow

### ISSUE THREAD

**Issue by fl34b4g** [mamorgen/magbot3#9]
I hope this is fixable since it would be a lifesaver.

The calendars are syncing really slow, it took a whole night for one week worths of classes to show up in Google Calendar... I've already input my data twice in Magbot.nl but that doesn't seem to do the trick.

I would really like some help!

**Comment by Netlob** [comment]
see https://github.com/mamorgen/magbot3/issues/10#issuecomment-537985130
